apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rok8s-example

spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rok8s-example
    spec:
      containers:
        - name: rok8s-example
          # `latest` will be replaced with $CI_SHA1 by k8s-deploy
          image: quay.io/maryg5/rok8s-practice:latest
          ports:
          - containerPort: 8080
            name: http
